[package]
name = "rust_chat_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = "0.9.1"
candle-transformers = "0.9.1"
hf-hub = { version = "0.3.2", features = ["tokio"] } # Enable tokio feature
tokio = { version = "1", features = ["full"] }
